---
title: "Månatlig nedladdningsstatistik av KB:s 10 mest nedladdade AI-modeller"
header-includes: 
 \usepackage{geometry}
 \geometry{left=0.40in, right=0.40in}
output:
  pdf_document:
    df_print: kable
date: "2022-12-17"
always_allow_html: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r maketable, include=FALSE}
library(ggplot2)
library(dplyr)

Sys.setlocale("LC_TIME", "C")

# dir.create("plots")
data_files <- list.files("data/models", full.names = TRUE)

df <- data_files %>%
  purrr::map_df(~readr::read_csv(.))

df_model <- df %>% 
  filter(model_name != "ALL-MODELS-MOVED-TO-KBLAB") %>%
  group_by(model_name, date) %>%
  summarize(downloads = sum(downloads)) %>%
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>%
  arrange(model_name, year, month) %>%
  ungroup()

df_model["month"] <- stringr::str_pad(df_model$month, side = "left", width = 2, pad = "0")
df_model["yearmonth"] <- paste(df_model$year, df_model$month, sep = "-")

df_table <- df_model %>%
  select(model_name, yearmonth, downloads) %>%
  tidyr::pivot_wider(names_from=yearmonth, values_from=downloads)
```

```{r kableknit, echo=FALSE, include=FALSE}
knitr::kable(df_table, booktabs = TRUE, longtable = TRUE) %>%
  kableExtra::column_spec(1, width="10em") %>%
  kableExtra::kable_styling(latex_options = c("hold_position", "repeat_header"),
                            position="center",
                            font_size=9)
```

```{r topmodels, echo=FALSE}
df_top <- df_model %>%
  filter(date >= "2023-01-01") %>%
  group_by(model_name) %>%
  summarize(total_downloads = sum(downloads)) %>%
  arrange(-total_downloads) %>%
  slice(1:10)

readr::write_csv(df_top, "kblab_top10_modeller_2023.csv")

df_model_top <- df_model %>%
  filter(model_name %in% df_top$model_name)

df_table_top <- df_model_top %>%
  filter(date >= "2023-01-01") %>%
  select(model_name, yearmonth, downloads) %>%
  tidyr::pivot_wider(names_from=yearmonth, values_from=downloads)

knitr::kable(df_table_top, booktabs = TRUE, longtable = TRUE) %>%
  kableExtra::column_spec(1, width="10em") %>%
  kableExtra::kable_styling(latex_options = c("hold_position", "repeat_header"),
                            position="center",
                            font_size=9)
```


```{r datasets, echo=FALSE}
data_files <- list.files("data/datasets", full.names = TRUE)

df <- data_files %>%
  purrr::map_df(~readr::read_csv(.))

df_dataset <- df %>% 
  filter(model_name != "ALL-MODELS-MOVED-TO-KBLAB") %>%
  group_by(model_name, date) %>%
  summarize(downloads = sum(downloads)) %>%
  mutate(year = lubridate::year(date),
         month = lubridate::month(date)) %>%
  arrange(model_name, year, month) %>%
  ungroup()

df_top <- df_dataset %>%
  filter(date >= "2023-01-01") %>%
  group_by(model_name) %>%
  summarize(total_downloads = sum(downloads)) %>%
  arrange(-total_downloads) %>%
  slice(1:10) %>%
  rename(dataset_name = model_name)

readr::write_csv(df_top, "kblab_top_datasets_2023.csv")
```